version: 0.2

phases:
  install:
    commands:
      - echo Installing yarn
      - sudo apt-get update -y && sudo apt-get install -y make apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update -y && sudo apt-get install -y yarn
      - yarn --version
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
      - echo Testing CI
      - export CI=true 
      - yarn test
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ s3://${BUCKET_NAME}
      - echo Build completed on `date`